name: moviedb
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_secure_storage: ^6.0.0
  json_annotation: ^4.6.0
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0
  cupertino_icons: ^1.0.2
  http: ^0.13.5
  youtube_player_flutter: ^8.1.0
  provider: ^6.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  json_serializable: ^6.3.1 
  build_runner: ^2.2.0

  flutter_lints: ^1.0.0

dependency_overrides:
  flutter_inappwebview:
    git:
      url: https://github.com/rshrc/flutter_inappwebview
      ref: master

flutter:

  uses-material-design: true

  assets:
    - images/
