name: moviedb
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_secure_storage: ^9.2.4
  json_annotation: ^4.9.0
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0
  cupertino_icons: ^1.0.8
  http: ^1.3.0
  youtube_player_flutter: ^9.1.1
  provider: ^6.1.4
  bloc: ^9.0.0
  flutter_bloc: ^9.0.0
  bloc_concurrency: ^0.3.0
  flutter_svg: ^2.0.17
  draggable_scrollbar: ^0.1.0
  animations: ^2.0.11
  toggle_switch: ^2.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  json_serializable: ^6.9.4 
  build_runner: ^2.4.15

  flutter_lints: ^5.0.0

dependency_overrides:
  flutter_inappwebview:
    git:
      url: https://github.com/rshrc/flutter_inappwebview
      ref: master

flutter:

  uses-material-design: true

  assets:
    - images/
